name: CI
on: [push]
jobs:
  # Testing Job
  Vitest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing modules...
        run: npm ci
      - name: Running tests...
        run: npm run test

  # Linting Job
  eslint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing modules
        run: npm ci
      - name: Running ESLint
        run: npm run lint